### ISSUE TITLE
Add Backpack to the Gravestone instead dropping it as item

### ISSUE THREAD

**Issue by Eufranio** [runescapejon/AdventureBackpack2#27]
In my server, I disabled the feature that places the backpack in the ground because it was causing some issues. Then, every time a player die, the Backpack is dropped as item, different from the other items that are stored in the Gravestone from OpenBlocks. The result is, the players get again their items from the grave, but the backpack sometimes despawn or is cleared...

**Comment by runescapejon** [comment]
I see the problem within the code I'll try my best to sort out this problem

**Comment by Ugachaga** [comment]
For now backpack placement fails if in radius of 12 cubes did not find full-sized solid block with empty space above it. So fluid (water/lava), air/emty_block or slabs (even snow) cause placement fail. Gonna fix it.

**Comment by Eufranio** [comment]
Fixed?

**Comment by runescapejon** [comment]
@Eufranio  please test this
https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.9fb21pre

**Comment by Sir-Chi** [comment]
I have tested the latest patch 21pre
I tested all backpacks with both modded and vanilla items & blocks in them, fluids as well when dieing and found no problems.
I also test the coal jetpack  - no problems
However the only problem i found is with the copter pack, when you die it still gets put in the grave however the area around where you died/around your grave still makes the copter sound (if you have it active when you die). Even when the grave is broken and you've put the pack back on.

I can do further test if you need, just ask.

**Comment by Ugachaga** [comment]
Thanks for the testing. Sound issue added to todo.
